name: Build WP Plugin

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install
        run: |
          yarn install --frozen-lockfile

      - name: archive
        run: |
          yarn archive

      - name: list package
        run: |
          ls -la package

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            package/*.zip